<?php
$collection = $block->getColletionTestimonials()->addFieldToFilter('is_active','1');
foreach ($collection as $key => $value) {
}
$contacts = $this->getColletionTestimonials();

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
  $BaseUrl=$storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_WEB);


?>

<a class="button" href="<?php echo $BaseUrl ?>testimonials/form">
    <span>Submit Your Testimonial</span>
</a>
<h2>Responsive Testimonials</h2>

<?php foreach ($contacts as $contact): ?>
    <div class="container">
      <img src="C:\xampp\htdocs\snakecodder\img\1.jpg" alt="Avatar" style="width:90px">
      <p><span><?php echo $contact->getName(); ?></span></p>
      <p><span><?php echo $contact->getcontent(); ?></span></p>
    </div>
 <?php endforeach; ?>

<?php 
$helper = \Magento\Framework\App\ObjectManager::getInstance()->get('SnakeCodder\Testimonials\Helper\Data'); 
if($helper->isEnable()) : ?>

Test

<?php endif; ?>