<div class="col-main">
<div id="messages_product_view"></div>
<div class="page-title">
    <h1>Submit your testimonial</h1>
</div>
<form action="http://demo.templates-master.com/extension02/default/testimonials/index/post/" id="testimonialForm" class="testimonialForm" method="post" enctype="multipart/form-data">
    <div class="fieldset">
        <h2 class="legend">Testimonial</h2>
        <ul class="form-list">
            <li class="fields">
                <div class="field">
                    <label for="name" class="required"><em>*</em>Name</label>
                    <div class="input-box">
                       <input name="name" id="name" title="Name" value="" class="input-text required-entry" type="text">
                    </div>
                </div>
                <div class="field">
                    <label for="email" class="required"><em>*</em>Email</label>
                    <div class="input-box">
                        <input name="email" id="email" title="Email" value="" class="input-text required-entry validate-email" type="text">
                    </div>
                </div>
                                    <div class="field">
                        <label for="company">Company</label>
                        <div class="input-box">
                            <input name="company" id="company" title="Company" value="" class="input-text" type="text">
                        </div>
                    </div>
                                                    <div class="field">
                        <label for="website">Website</label>
                        <div class="input-box">
                            <input name="website" id="website" title="Website" value="" class="input-text" type="text">
                        </div>
                    </div>
                                                    <div class="field">
                        <label for="twitter">Twitter</label>
                        <div class="input-box">
                            <input name="twitter" id="twitter" title="Twitter" value="" class="input-text" type="text">
                        </div>
                    </div>
                                                    <div class="field">
                        <label for="facebook">Facebook</label>
                        <div class="input-box">
                            <input name="facebook" id="facebook" title="Facebook" value="" class="input-text" type="text">
                        </div>
                    </div>
                                <div class="field">
                    <label for="image">Profile image</label>
                    <div class="input-box">
                        <input name="image" id="image" title="Image" type="file">
                    </div>
                </div>
                <div class="field">
                    <label>Rating</label>
                    <div class="input-box">
                                            <label for="rating_1">1                            <input type="radio" name="rating" id="rating_1" value="1" class="radio">
                        </label>
                                            <label for="rating_2">2                            <input type="radio" name="rating" id="rating_2" value="2" class="radio">
                        </label>
                                            <label for="rating_3">3                            <input type="radio" name="rating" id="rating_3" value="3" class="radio">
                        </label>
                                            <label for="rating_4">4                            <input type="radio" name="rating" id="rating_4" value="4" class="radio">
                        </label>
                                            <label for="rating_5">5                            <input type="radio" name="rating" id="rating_5" value="5" class="radio">
                        </label>
                                        </div>
                </div>
            </li>
            <li class="wide">
                <label for="message" class="required"><em>*</em>Message</label>
                <div class="input-box">
                    <textarea name="message" id="message" title="Message" class="required-entry input-text" cols="5" rows="3"></textarea>
                </div>
            </li>
                    </ul>
    </div>
    <div class="buttons-set">
        <p class="required">* Required Fields</p>
        <input type="text" name="hideit" id="hideit" value="" style="display:none !important;">
        <button type="submit" title="Submit" class="button"><span><span>Submit</span></span></button>
        <button class="button" onclick="setLocation('http://demo.templates-master.com/extension02/default/testimonials/'); return false;">
            <span><span>Back</span></span>
        </button>
    </div>
</form>
<script type="text/javascript">
//<![CDATA[
    var testimonialForm = new VarienForm('testimonialForm', true);
//]]>
</script>                </div>